# Generated by Django 4.1.3 on 2023-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('mfgdate', models.DateTimeField(auto_now_add=True)),
                ('expdate', models.DateTimeField(blank=True, null=True)),
                ('costperpro', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
