# Generated by Django 4.1.3 on 2023-04-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0007_users_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
