# Generated by Django 4.1.3 on 2023-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0010_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
