# Generated by Django 4.1.3 on 2023-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0011_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
