# Generated by Django 4.1.3 on 2023-05-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0013_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
