# Generated by Django 4.1.3 on 2023-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0014_alter_users_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
