# Generated by Django 4.1.3 on 2023-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0016_alter_users_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.TextField(default={'objects': []}),
        ),
    ]
