# Generated by Django 4.1.3 on 2023-05-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0017_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='Product',
        ),
    ]
