# Generated by Django 4.1.3 on 2023-05-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0018_rename_product_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
