# Generated by Django 4.1.3 on 2023-05-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0020_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartitem',
        ),
    ]
