# Generated by Django 4.1.3 on 2023-05-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0022_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
