# Generated by Django 4.1.3 on 2023-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0025_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
