# Generated by Django 4.1.3 on 2023-05-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0028_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_no',
            new_name='phoneno',
        ),
    ]
