# Generated by Django 4.1.3 on 2023-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0029_rename_phone_no_users_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatch'), (3, 'On the way'), (4, 'Delivered'), (5, 'Cancel'), (6, 'Return')], default=1),
        ),
    ]
