# Generated by Django 4.1.3 on 2023-05-16 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lishapp', '0030_booking_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='UserProfile',
        ),
    ]
