# Generated by Django 4.1.3 on 2023-05-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0031_rename_users_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
