# Generated by Django 4.1.3 on 2023-05-21 10:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0033_remove_carousel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=tinymce.models.HTMLField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=False),
        ),
    ]
