# Generated by Django 4.1.3 on 2023-05-23 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0035_remove_product_mfgdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfgdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
