# Generated by Django 4.1.3 on 2023-05-24 05:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0036_product_mfgdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
