# Generated by Django 4.1.3 on 2023-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0037_alter_product_description_alter_userprofile_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
