# Generated by Django 4.1.3 on 2023-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0041_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'This category has already been added.'}, max_length=100, unique=True),
        ),
    ]
