# Generated by Django 4.1.3 on 2023-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0046_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash on deliver', 'cash on delivery'), ('khalti', 'khalti')], default='Cash on delivery', max_length=100)),
                ('payment_created', models.BooleanField(blank=True, default=False, null=True)),
                ('product_completed', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
